apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/namespaces/chat.yaml
  - apps/chat/backend
  - apps/chat/database
  - apps/chat/frontend
  - apps/chat/ingress
  - apps/chat/policies 
