apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
      - name: frontend
        image: sohail28/chat-frontend:v2
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: http://chat-backend:5000
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

      volumes:
      - name: nginx-config
        configMap:
          name: chat-frontend-nginx-config

